# -*- coding: utf-8 -*-
"""pneumonia-detection using CNN(collab).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ou3B-JZJKjLZDRCeovFhAP_ttbnDDWss

# pneumonia detection using CNN

# 1. Install Required Libraries
"""

!pip install tensorflow keras matplotlib numpy scikit-learn

"""# importing libraries"""

import os
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Flatten, Dense, Dropout

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

"""# Download Dataset via KaggleHub"""

import kagglehub
import shutil
from pathlib import Path

# Download latest version
path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")

# Copy to working directory
DESTINATION = Path("chest-xray-pneumonia_dataset")
DESTINATION.mkdir(parents=True, exist_ok=True)
shutil.copytree(path, str(DESTINATION), dirs_exist_ok=True)

print("Dataset saved to:", DESTINATION)

"""# Set Dataset Paths"""

dataset_path = path + "/chest_xray"

train_dir = dataset_path + "/train"
val_dir = dataset_path + "/val"
test_dir = dataset_path + "/test"

print(train_dir)
print(val_dir)
print(test_dir)

print("Train:", train_data.class_indices)
print("Validation:", val_data.class_indices)
print("Test:", test_data.class_indices)

"""#  Data Augmentation and Data Preprocessing"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator


train_datagen = ImageDataGenerator(
    rescale=1./255,

    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,

    shear_range=0.2,
    zoom_range=0.2,

    horizontal_flip=True
)


val_datagen = ImageDataGenerator(
    rescale=1./255
)

"""# Load Dataset"""

train_data = train_datagen.flow_from_directory(
    "/content/chest-xray-pneumonia_dataset/chest_xray/train",
    target_size=(128,128),
    batch_size=32,
    class_mode="binary"
)


val_data = val_datagen.flow_from_directory(
    "/content/chest-xray-pneumonia_dataset/chest_xray/val",
    target_size=(128,128),
    batch_size=32,
    class_mode="binary"
)


test_data = val_datagen.flow_from_directory(
    "/content/chest-xray-pneumonia_dataset/chest_xray/test",
    target_size=(128,128),
    batch_size=32,
    class_mode="binary",
    shuffle=False
)

"""# Build CNN Model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Flatten, Dense, Dropout


model = Sequential()


model.add(Conv2D(
    32,
    (3,3),
    activation='relu',
    input_shape=(128,128,3)
))

model.add(MaxPooling2D())


model.add(Conv2D(
    64,
    (3,3),
    activation='relu'
))

model.add(MaxPooling2D())


model.add(Flatten())


model.add(Dropout(0.5))


model.add(Dense(
    128,
    activation='relu'
))


model.add(Dropout(0.5))


model.add(Dense(
    1,
    activation='sigmoid'
))

"""# Compile Model"""

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""# Train Model"""

from tensorflow.keras.callbacks import EarlyStopping


early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)


history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=30,
    callbacks=[early_stop]
)

"""# check my model is overfit or not"""

# Final training accuracy
train_accuracy = history.history['accuracy'][-1]

# Final validation accuracy
val_accuracy = history.history['val_accuracy'][-1]


print("Training Accuracy:", train_accuracy * 100)
print("Validation Accuracy:", val_accuracy * 100)

"""# Evaluate Model"""

loss, accuracy = model.evaluate(test_data)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy * 100, "%")

"""# Classification Report"""

from sklearn.metrics import classification_report


# Prediction on test data

pred = model.predict(test_data)


# Convert probabilities to classes

y_pred = (pred > 0.5).astype(int).reshape(-1)



# Classification report

print(
    classification_report(
        test_data.classes,
        y_pred,
        target_names=["NORMAL", "PNEUMONIA"]
    )
)

"""# Confusion Matrix"""

cm = confusion_matrix(
    test_data.classes,
    y_pred
)

print(cm)
plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""#  Accuracy and Loss Graphs"""

import matplotlib.pyplot as plt


# Accuracy graph

plt.figure(figsize=(8,5))

plt.plot(history.history['accuracy'])

plt.plot(history.history['val_accuracy'])

plt.xlabel("Epochs")
plt.ylabel("Accuracy")

plt.legend(["Training Accuracy","Validation Accuracy"])

plt.title("Training vs Validation Accuracy")

plt.show()



# Loss graph

plt.figure(figsize=(8,5))

plt.plot(history.history['loss'])

plt.plot(history.history['val_loss'])

plt.xlabel("Epochs")
plt.ylabel("Loss")

plt.legend(["Training Loss","Validation Loss"])

plt.title("Training vs Validation Loss")

plt.show()

"""# Save Model"""

from tensorflow.keras.models import load_model

loaded_model = load_model("pneumonia_model.keras")

print("Model Loaded Successfully")

"""# Predict New X-Ray"""

print(train_data.class_indices)

from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np


img_path = "/content/chest-xray-pneumonia_dataset/chest_xray/train/PNEUMONIA/person1002_bacteria_2933.jpeg"


# Load image
img = image.load_img(
    img_path,
    target_size=(128,128)
)


# Convert to array
img_array = image.img_to_array(img)


# Normalize
img_array = img_array / 255.0


# Add batch dimension
img_array = np.expand_dims(img_array, axis=0)



# Prediction
prediction = model.predict(img_array)


confidence = prediction[0][0]


print("Raw Prediction:", confidence)



# Correct class mapping
if confidence >= 0.5:

    result = "PNEUMONIA"
    score = confidence

else:

    result = "NORMAL"
    score = 1 - confidence



# Show image

plt.figure(figsize=(6,6))

plt.imshow(img)

plt.title(
    f"Prediction: {result}\nConfidence: {score*100:.2f}%"
)

plt.axis("off")

plt.show()


print("Prediction:", result)
print("Confidence:", f"{score*100:.2f}%")